# Generated by Django 5.0 on 2024-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
