# Generated by Django 5.0 on 2024-01-19 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
    ]
